"""Generate docs/action-reference.md from action.yml and the reusable workflow.

The reference is a build product, not a hand-maintained page: chargate's README and its
generated reference had already drifted about a default before anyone noticed. Run with
``--check`` in CI to fail when the committed file no longer matches the source.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ACTION = ROOT / "action.yml"
WORKFLOW = ROOT / ".github" / "workflows" / "docs.yml"
OUT = ROOT / "docs" / "action-reference.md"


def cell(text: str | None) -> str:
    """Collapse whitespace and escape what would otherwise break the table.

    A `|` inside a cell starts a new column. Descriptions here legitimately contain
    them — ``auto | uv | pip`` is how the choices read — and unescaped they made
    markdownlint report "Too many cells, extra data will be missing", which is exactly
    what rendered: the tail of every such description was dropped from the page.
    """
    collapsed = re.sub(r"\s+", " ", (text or "").strip()).replace("|", r"\|")

    # `<repo>` outside a code span is parsed as an HTML tag and disappears from the page
    # — the same silent content loss the pipe escaping above exists to stop. Escape only
    # OUTSIDE backticks: inside a code span the angle brackets are already literal, and
    # `&lt;` there would render as the entity itself.
    parts = collapsed.split("`")
    for i in range(0, len(parts), 2):  # even indexes are outside code spans
        parts[i] = parts[i].replace("<", "&lt;").replace(">", "&gt;")
    collapsed = "`".join(parts)

    # An empty cell renders as `|  |`, which markdownlint flags as bad column style and
    # which reads as a missing value rather than a deliberate one.
    return collapsed or "—"


def default(value: object) -> str:
    return f"`{value}`" if value not in ("", None) else "not set"


def workflow_inputs() -> dict:
    doc = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    # `on:` parses as the boolean True in YAML 1.1, which is why this is not doc["on"].
    trigger = doc.get(True, doc.get("on"))
    return trigger["workflow_call"]["inputs"]


def render() -> str:
    action = yaml.safe_load(ACTION.read_text(encoding="utf-8"))
    wf_in = workflow_inputs()

    assert not any(  # nosec: B101 — generator script, not bytecode-optimised; guards a doc invariant
        spec.get("required") for spec in action["inputs"].values()
    ), "action.yml has a required input — update the prose in render() to match"

    lines = [
        "# Action reference",
        "",
        "<!-- sources: action.yml, .github/workflows/docs.yml -->",
        "",
        "Generated by `scripts/gen_action_reference.py`. Edit `action.yml` or the reusable",
        "workflow, not this page. For the task-shaped version, see [Setup](setup.md).",
        "",
        "## Action inputs",
        "",
        f"`MagmaMoose/tremvok@v1` — all {len(action['inputs'])} inputs are optional.",
        "",
        "| Input | Default | Description |",
        "| --- | --- | --- |",
    ]
    for key, spec in action["inputs"].items():
        lines.append(
            f"| `{key}` | {default(spec.get('default'))} | {cell(spec.get('description'))} |"
        )

    lines += ["", "## Action outputs", "", "| Output | Description |", "| --- | --- |"]
    for key, spec in action["outputs"].items():
        lines.append(f"| `{key}` | {cell(spec.get('description'))} |")

    lines += [
        "",
        "## Workflow inputs",
        "",
        "`MagmaMoose/tremvok/.github/workflows/docs.yml@v1` — the action's inputs, plus the",
        "two that only a workflow can act on.",
        "",
        "| Input | Type | Default | Description |",
        "| --- | --- | --- | --- |",
    ]
    for key, spec in wf_in.items():
        lines.append(
            f"| `{key}` | `{spec.get('type', 'string')}` | {default(spec.get('default'))} "
            f"| {cell(spec.get('description'))} |"
        )

    lines += [
        "",
        "## Required permissions",
        "",
        "Declared by the **caller**, because a composite action cannot declare",
        "`permissions:`:",
        "",
        "```yaml",
        "permissions:",
        "  contents: read      # checkout",
        "  pages: write        # actions/deploy-pages",
        "  id-token: write     # actions/deploy-pages",
        "```",
        "",
        "With `publish: false` only `contents: read` is needed.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args(argv)

    generated = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != generated:
            print(f"{OUT.relative_to(ROOT)} is stale. Run: python scripts/gen_action_reference.py")
            return 1
        print("action-reference.md is up to date")
        return 0
    OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
